<a href="https://colab.research.google.com/github/andryasilvestre/Data-Science-Senac/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1ª AULA DATA SCIENCE (02.03.2023)



Importanto e apelidando a NumPy

In [ ]:
import numpy as np

Meios de criar uma lista

In [ ]:
minhaLista = [0,1,2,3,4,5,6,7,8]


In [ ]:
minhaLista2 = list(range(9))

Meios de transformar a lista em um Array Numpy

In [ ]:
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Fazendo as etapas anteriores numa única sintaxe

In [ ]:
array2=np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Imprimindo os arrays

In [ ]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


In [ ]:
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Start, stop, step:

In [ ]:

array31 = np.arange(0, 10, 0.5)
array31

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
array81 = np.arange(0, 10, -0.5)
array81

array([], dtype=float64)

Arredondando os valores obtidos:

novoArray = np.around(array3)
novoArray

Também podemos "forçar" o tipo dos elementos: >>> mas dá errado pois:

In [ ]:
array3 = np.arange(0, 10, 0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Arredondando os valores obtidos: 

In [ ]:
novoArray = np.around(array31)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [ ]:
array32 = np.arange(0, 10, 1.5, dtype = float)
array32

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

Também podemos pré determinar o tipo dos elementos

In [ ]:
array4 = np.arange(12)

Acima, temos inteiros, mas pode deixar o array preparado para trabalhar com tipos float:

In [ ]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Verificando o tipo do objeto

In [ ]:
type(array4)

numpy.ndarray

Verificando o tipo dos elementos do Array

In [ ]:
array4.dtype

dtype('float64')

In [ ]:
#OU...

print(array4.dtype)

float64


Também podemos criar um array digitando os valores:

In [ ]:
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

[0 1 2 3 4]


Selecionando um elemento específico:

In [ ]:
vetor1[3]

3

Selecionando um intervalo específico

In [ ]:
vetor1[0:2]

array([0, 1])

Ou também

In [ ]:
print(vetor1[0:2])

[0 1]


Criando um array de strings:

In [ ]:
s = np.array(['Python', 'Profissional', 'Java', 'Água'])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [ ]:
s = np.array(['Python', 12345612, 'Profissional', 'Java', 'Água'])
s
#Transforma o número em string

array(['Python', '12345612', 'Profissional', 'Java', 'Água'], dtype='<U21')

Alterando um elemento do Array:

In [ ]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

Vamos tentar incluir elementos:


In [ ]:
vetor1[0] = 'Novo elemento'
vetor1

ValueError: ignored

Agora tente o seguinte:

In [ ]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])

O que aconteceu?